frontend:
  url: http://localhost:5173

backend:
  url: http://localhost:8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:~/xbook
    username: sax
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: local
  h2:
    console:
      path: /h2-console
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: socialxbook@gmail.com
    password: "xury imwo eruf pmxy"