spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  datasource:
#    url: jdbc:postgresql://flora.db.elephantsql.com:5432/vcsujows?user=vcsujows&password=zeHF8ukrUJKFGklM_GIZCQfczl323dhM
#    username: vcsujows
#    password: zeHF8ukrUJKFGklM_GIZCQfczl323dhM
#    driver-class-name: org.postgresql.Driver
  datasource:
      url: jdbc:postgresql://xbookbase-1.cvgsqg8ceiei.us-east-1.rds.amazonaws.com:5432/xbook
      username: postgres
      password: 123 # Ask for password
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: prod
  h2:
    console:
      path: /h2-console
      enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: socialxbook@gmail.com
    password: 123  #Ask for password



