spring:
  datasource:
    url: jdbc:h2:/src/main/resources/xbook.db
    username: sax
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: local
  h2:
    console:
      path: /h2-console
      enabled: true