spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: #Ask for
    username: #Ask for
    password: #Ask for
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never
  config:
    activate:
      on-profile: prod
  h2:
    console:
      path: /h2-console
      enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: socialxbook@gmail.com
    password: 123  #Ask for password



