name: CI

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  java-ci-checks:
    name: Automated Java CI checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Compile and run tests with Maven
        run: mvn -f xbook-api/pom.xml clean test
        
  javascript-ci-checks:
      name: Automated Javascript CI checks
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Cache node modules
          uses: actions/cache@v3
          env:
            cache-name: cache-node-modules
          with:
            path: ~/.npm
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
               ${{ runner.os }}-build-${{ env.cache-name }}-
               ${{ runner.os }}-build-
               ${{ runner.os }}-
  
        - name: Setup Node.js 20.12.0
          uses: actions/setup-node@v3
          with:
            node-version: 20.12.0
  
        - name: Install dependencies
          run: npm install --prefix xBook-FrontEnd
  
        - name: Run build
          run: npm run build --prefix xBook-FrontEnd
